# Project configuration
general:
  productiveBranch: 'master'

stages:
  Release:
    tmsUpload: true

# Step configuration
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      credentialsId: 'presalesauth'
      apiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
      org: 'SAP Presales Cloud (NEO/FOUNDRY)_sapshowcase'
      space: 'DEV'
